name: Price Bot 5 min Check

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes UTC
  workflow_dispatch:     # Allows manual testing

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install libraries
        run: pip install -r requirements.txt

      - name: Run Bot and Check Price
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
          DESTINATION_EMAIL: ${{ secrets.DESTINATION_EMAIL }}
        run: python price_bot.py
        
      - name: Upload Price History
        uses: actions/upload-artifact@v3
        with:
          name: price-history-data
          path: price_history.csv
